# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [1]:
str_1 = "ada"
str_2 = "lovelace"
str_3 = "was considered the world's first computer programmer."


In [2]:
a=[i[0].upper() + i[1:] for i in [str_1,str_2]]
print(a[0]+' ' + a[1]+ " " + str_3)

Ada Lovelace was considered the world's first computer programmer.


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [3]:
str_1 = "  was considered the world's first computer programmer.  "


In [4]:
str_1[2:-2]

"was considered the world's first computer programmer."

3. Найти первое вхождение в строку подстроки (☆☆☆)

In [5]:
str_1 = "But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
str_2 = "you"


In [6]:
str_1.find(str_2)


7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [7]:
str_1 = "Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"



In [8]:
str_1=str_1.split('#')
str_1

['Holy',
 'cow,',
 'Rick!',
 'I',
 'didn’t',
 'know',
 'hanging',
 'out',
 'with',
 'you',
 'was',
 'making',
 'me',
 'smarter!']

5. Полученный массив строк склеить через пробел (★☆☆)

In [9]:
' '.join(str_1)

'Holy cow, Rick! I didn’t know hanging out with you was making me smarter!'

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [10]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}



In [11]:
len(personal_data)

3

In [12]:
for i in range(1,len(personal_data)+1):
    print(f'{personal_data.get(i)[0]} (age {personal_data.get(i)[1]}) is a {personal_data.get(i)[2]}')

Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [13]:
a=int(input())
if (a%4 == 0 and a%100 != 0 )or a%400 == 0:
    print('YES')
else:
    print('NO')

 2222


NO


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [14]:
words = ['Not', 'my', 'cup', 'of', 'tea']



In [15]:
{x:y for x,y in enumerate(words)}

{0: 'Not', 1: 'my', 2: 'cup', 3: 'of', 4: 'tea'}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [16]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']


In [17]:
dogs.pop(1)
# второй вариант удаления ниже
#dogs.remove('australian cattle dog')

'australian cattle dog'

In [18]:
dogs

['border collie', 'labrador retriever']

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [19]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']



In [20]:
[i.upper() for i in dogs[3:6]]

['CATTLE', 'DOG', 'LABRADOR']

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [21]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

   

In [22]:
spisok=[]
for name in pets.keys():
    a = name
    for y in pets[name]:
        a=a+' '+ str(pets[name].get(y))
    spisok.append(a)

In [23]:
[print(format(i)) for i in spisok]

willie dog eric True
walter cockroach eric False
peso dog chloe True


[None, None, None]

12. Проверить является ли множество подмножеством другого множества. Множества придумываем самостоятельно  (★☆☆)

In [24]:
a = {1,2,3,4}
b = {1,2}

In [25]:
b <= a

True

13. Объединить несколько множеств. Множества придумываем самостоятельно (★☆☆)

In [26]:
a = {1,2,3,4}
b = {5,6}

In [27]:
z=a.union(b)
z

{1, 2, 3, 4, 5, 6}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [28]:
#введем множество b
b={1,2,3,6,7}

In [29]:
z

{1, 2, 3, 4, 5, 6}

In [30]:
# найдем пересечение
b.intersection(z)

{1, 2, 3, 6}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. Множества придумываем самостоятельно(★★☆)

(hint: .symmetric_difference())

In [31]:
a = {1,2,3,4}
b = {1,2,5,6}

In [32]:
a.symmetric_difference(b)

{3, 4, 5, 6}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [33]:

#закоментил файл с моего ноутбука
file = 'data/credit_sample.txt'
#file = '/Users/andrejglavniy/Documents/test.txt'

In [34]:
with open(file) as f:
    spisok = [line.replace('\n','').split(',') for line in f.readlines()]
f.close()
#создадим словарь
voca = {}
#нвесем все данные
for i, row in enumerate(spisok):
    if row != spisok[0]:
        voca[row[0]] = row[1:]
#взглянем на словарь
voca

{'Adrianov': ['25', '30000', 'artist'],
 'Avanov': ['22', '2435345', 'it'],
 'Popov': ['28', '30500', 'hr'],
 'Sdvadov': ['29', '33000', 'artist'],
 'Dddddsa': ['30', '3800', 'it']}

In [35]:
#посчитаем уникальные работы
counter = len(set([y[-1] for i,y in voca.items()]))
counter

3

In [36]:
#добавляем значение подсчета в словарь
voca['counter'] = counter

In [37]:
#запишем результат в json
import json
with open('data.json', 'w') as j:
    json.dump(voca, j)

### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [38]:
import os

опишу ; у меня нет папки гиф. создавал новую папку, доабвлял файлы , оставил только гиф , затем все поудалял.

In [39]:
#cохраняем изначальную длиректорию
a=os.getcwd()
a

'/Users/andrejglavniy'

In [40]:
#создаем папку gifs
os.mkdir("gifs")

In [41]:
#меняем директорию
os.chdir(os.getcwd()+'/gifs/')

In [42]:
text_file = open("text.txt", "w")
# запить текста в этот файл
text_file.write("Это текстовый файл")
text_file.close()

In [43]:
gif_file = open("sdada.gif", "w")
# запить гифа в этот файл
gif_file.close()

In [44]:
dir_list = os.listdir(os.getcwd())
dir_list

['text.txt', 'sdada.gif']

In [45]:
for x in dir_list:
    if x.endswith(".gif"):
        print(x)
    else:
        print(x)
        os.remove(x)

text.txt
sdada.gif


In [46]:
#проверяем наш цикл и что остались только гифы
os.listdir(os.getcwd())

['sdada.gif']

In [47]:
os.remove(os.listdir(os.getcwd())[0])

In [48]:
os.chdir(a)

In [49]:
#удаляем папку gifs
os.rmdir("gifs")

18. Создать папку с названием temp и удалить её (★☆☆)

In [50]:
os.mkdir("temp")

In [51]:
'temp' in os.listdir()

True

In [52]:
# Удаление папки
os.rmdir("temp")

In [53]:
#проверка, что папка удалена
'temp' in os.listdir()

False

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [54]:
for i in os.environ:
    print(i)

__CFBundleIdentifier
TMPDIR
XPC_FLAGS
TERM
SSH_AUTH_SOCK
XPC_SERVICE_NAME
TERM_PROGRAM
TERM_PROGRAM_VERSION
TERM_SESSION_ID
SHELL
HOME
LOGNAME
USER
PATH
SHLVL
PWD
OLDPWD
HOMEBREW_PREFIX
HOMEBREW_CELLAR
HOMEBREW_REPOSITORY
MANPATH
INFOPATH
CONDA_EXE
_CE_M
_CE_CONDA
CONDA_PYTHON_EXE
CONDA_SHLVL
CONDA_PREFIX
CONDA_DEFAULT_ENV
CONDA_PROMPT_MODIFIER
LC_CTYPE
_
PYDEVD_USE_FRAME_EVAL
JPY_SESSION_NAME
JPY_PARENT_PID
CLICOLOR
FORCE_COLOR
CLICOLOR_FORCE
PAGER
GIT_PAGER
MPLBACKEND


20. Как игнорировать warrnings?

In [55]:
import warnings
warnings.filterwarnings("ignore")

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [56]:
from datetime import date
from datetime import datetime
from datetime import timedelta

In [57]:
#вывод сегодня/вчера/завтра
[print(date.today() + timedelta(i)) for i in [0,-1,1]]

2023-10-04
2023-10-03
2023-10-05


[None, None, None]

22. Вывести день недели сегодняшней даты (★☆☆)

In [58]:
days = ['понедельник','вторник','среда','четверг','пятница','суббота','воскресеье']
print(days[date.today().weekday()])
date.today().strftime('%A')

среда


'Wednesday'

23. Получить список дат за предыдущую неделю (★★☆)

In [59]:
#Узнаем сегодняшний день недели и записывапем в перменную
today=date.today().weekday()
#получем даты за прошлую неделю, в таймдельта складываем сегодняшний день и итерацию 
itog = [date.today() - timedelta(today+i) for i in range(1,8)]

{print(i) for i in itog}

2023-10-01
2023-09-30
2023-09-29
2023-09-28
2023-09-27
2023-09-26
2023-09-25


{None}

24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [60]:
datetime.now().strftime('%d.%m.%Y %H:%M:%S')

'04.10.2023 02:01:35'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [61]:
#выше мы уже узнали сегодняшний день
#получем даты за прошлую неделю, в таймдельта складываем сегодняшний день и 7, так как нужен понедельник. 
last_monday = date.today() - timedelta(today+7)
print(last_monday)

2023-09-25


# Numpy

In [62]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [63]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [64]:
#size - размер массива, itemsize - 1 элемент в байтах
a.size * a.itemsize

80

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [65]:
# создадим копию вектора
b=a.copy()

In [66]:
b[4] =1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [67]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [68]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [69]:
np.flip(a)

array([4, 3, 2, 1])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [70]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [71]:
a=np.array([1,2,0,0,4,0])

In [72]:
a

array([1, 2, 0, 0, 4, 0])

In [73]:
np.nonzero(a)

(array([0, 1, 4]),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [74]:
a=np.arange(0,100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
a.max()

99

In [76]:
a.min()

0

In [77]:
a.mean()

49.5

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [78]:
a=np.zeros(64)

In [79]:
#создадим цикл для добавление 1 , при нечетном без сдвига .
for i in range(8):
    if i %2 != 0:
        a[i*8:(i*8+8):2] =1
    else:
        a[(i*8+1):(i*8+8):2] =1

In [80]:
a.reshape(8,8)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [81]:
# создадим матрицу
a=np.arange(25).reshape(5,5)
# нормалищуем
a = (a - a.mean())/np.std(a)

In [82]:
a

array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [83]:
#create the first array
a = np.arange(10)
#create second array
b = np.arange(15)

In [84]:
np.intersect1d(a,b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [85]:
#create random array
a = np.random.rand(15)
a

array([6.02250653e-01, 8.03596871e-02, 8.60805106e-04, 4.66128909e-01,
       8.34154710e-01, 3.65712319e-01, 7.32177636e-01, 3.76885159e-01,
       2.50029600e-02, 5.07131094e-01, 8.73102566e-01, 8.63235500e-01,
       6.34897395e-01, 3.90084056e-01, 5.96291110e-01])

получилось найти 6

In [86]:
a.round()

array([1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.])

In [87]:
a.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
np.ceil(a)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
np.floor(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
np.trunc(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
np.rint(a)

array([1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.])

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [92]:
a = np.random.rand(10)
a

array([0.75113268, 0.23749865, 0.10451864, 0.41397444, 0.97728304,
       0.83953569, 0.34284046, 0.27408377, 0.60858055, 0.02701713])

In [93]:
np.sort(a)

array([0.02701713, 0.10451864, 0.23749865, 0.27408377, 0.34284046,
       0.41397444, 0.60858055, 0.75113268, 0.83953569, 0.97728304])

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [94]:
#create the first array
a = np.random.rand(10)
#create second array
b = np.random.rand(10)
print(a)
print(b)

[0.69679468 0.97535562 0.93383416 0.7282958  0.97220814 0.05619225
 0.91151953 0.58492267 0.9158047  0.7294781 ]
[0.88570413 0.52796967 0.40239462 0.3752449  0.23445596 0.3648105
 0.66263335 0.04063715 0.20947115 0.45243492]


In [95]:
np.array_equal(a,b)

False

In [96]:
# прверим поэлементно , с параметром абсолют. допуска 1.
np.allclose(a,b, atol= 1 )

True

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [97]:
a = np.random.uniform(5,10, 10)

In [98]:
a

array([9.21626773, 8.35296866, 8.43394685, 9.17273758, 6.21995883,
       5.54486287, 7.29712319, 9.33811006, 7.03684688, 8.39978254])

In [99]:
# меняем макс знач.
a[np.argmax(a)] = -1

In [100]:
a

array([ 9.21626773,  8.35296866,  8.43394685,  9.17273758,  6.21995883,
        5.54486287,  7.29712319, -1.        ,  7.03684688,  8.39978254])

16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [101]:
# массив
a

array([ 9.21626773,  8.35296866,  8.43394685,  9.17273758,  6.21995883,
        5.54486287,  7.29712319, -1.        ,  7.03684688,  8.39978254])

In [102]:
#зададим рандомное число
b=np.random.choice(a)
b

7.297123185284775

In [103]:
#найдем значение индекса рандомного числа и запишем в переменную
index_rand = np.where(a==b)[0][0]
index_rand

6

In [104]:
#если рассматривать самый близкий эл-т по индексу, то
if abs(a[index_rand] - a[index_rand-1]) < abs(a[index_rand] - a[index_rand+1]):
    print(a[index_rand-1])
else:
    print(a[index_rand+1])

5.544862869889505


In [105]:
#если рассматривать самый близкий эл-т по значению, то сначала отсортируем
a=np.sort(a)
a

array([-1.        ,  5.54486287,  6.21995883,  7.03684688,  7.29712319,
        8.35296866,  8.39978254,  8.43394685,  9.17273758,  9.21626773])

In [106]:
index_rand = np.where(a==b)[0][0]
index_rand

4

In [107]:
if abs(a[index_rand] - a[index_rand-1]) < abs(a[index_rand] - a[index_rand+1]):
    print(a[index_rand-1])
else:
    print(a[index_rand+1])

7.036846878195858


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [108]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
np.mean(a, axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [110]:
#создадим массив
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:
def func_mean(a,window=3):
    #a -список, цindow - окно для скольязящего среднего
    return np.array([np.sum(a[i:window+i])/window for i in range(len(a)-window)])

In [112]:
func_mean(a)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

<img src="gifs/bender.gif" width="400">

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

2. Напишите паттерн для поиска строки содержащей только буквы в верхнем и нижнем регистре, цифры и подчеркивание

3. Сделайте регистронезависимую замену(replace) во входной строке